dist: xenial

install:
  - sudo apt-get install make curl jq

script:
  - GITHUB_TOKEN=$GITHUB_TOKEN make build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: public
  fqdn: buildpacks.io
  skip_cleanup: true
  verbose: true
  on:
    branch: master
