dist: xenial

install:
  - sudo apt-get install make curl jq
  - wget https://github.com/gohugoio/hugo/releases/download/v0.64.1/hugo_extended_0.64.1_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - GITHUB_TOKEN=$GITHUB_TOKEN make build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: public
  fqdn: buildpacks.io
  skip_cleanup: true
  verbose: true
  on:
    branch: master
