baseURL = "https://buildpacks.io/"
languageCode = "en-us"

title = "Cloud Native Buildpacks"
theme = "buildpacks"

pygmentsUseClasses = true
pygmentsCodefences = true

[markup.goldmark.renderer]
unsafe= true

[params]
twitter_handle = "buildpacks_io"
github_base_url = "https://github.com/buildpacks"
slack_invite_url = "https://slack.buildpacks.io/"
description = "Cloud Native Buildpacks transform your application source code into images that can run on any cloud."

[menu]
  [[menu.main]]
  identifier = "home"
  name       = "Home"
  url        = "/"
  weight     = 1

  [[menu.main]]
  identifier = "features"
  name       = "Features"
  url        = "/features"
  weight     = 2

  [[menu.main]]
  identifier = "docs"
  name       = "Docs"
  url        = "/docs"
  weight     = 3

  [[menu.main]]
  identifier = "blog"
  name       = "Blog"
  url        = "https://medium.com/buildpacks"
  weight     = 4
